import type { ExerciseContext } from "./model";

/**
 * Starter exercise list for search. Anything typed that isn't here is saved as-is
 * and shows up in search from then on.
 * [stable ID, name, section hint, aliases]
 */
export type Seed = [string, string, ExerciseContext | "any", string?];

export const SEEDS: Seed[] = [
  // mobility / warm-up / physio
  ["seed:0001", "Cat cow", "warmup", "cat camel spine"],
  ["seed:0002", "Standing knee to chest", "warmup"],
  ["seed:0003", "Kneeling knee to chest", "warmup"],
  ["seed:0004", "Plank knee to elbow", "warmup", "mountain climber"],
  ["seed:0005", "Dead bug", "warmup", "core"],
  ["seed:0006", "Bird dog", "warmup", "core"],
  ["seed:0007", "Side plank", "warmup", "core"],
  ["seed:0008", "Plank", "warmup", "core front"],
  ["seed:0009", "Glute bridge", "warmup", "hip band"],
  ["seed:0010", "Single-leg glute bridge", "warmup", "hip"],
  ["seed:0011", "Clamshell", "warmup", "hip band"],
  ["seed:0012", "McGill curl-up", "warmup", "core big 3"],
  ["seed:0013", "Pallof press", "warmup", "core anti-rotation cable band"],
  ["seed:0014", "Copenhagen plank", "warmup", "adductor core"],
  ["seed:0015", "Hip flexor stretch", "warmup", "kneeling lunge stretch"],
  ["seed:0016", "90/90 hip switch", "warmup", "hip mobility"],
  ["seed:0017", "World's greatest stretch", "warmup"],
  ["seed:0018", "Thoracic rotation", "warmup", "t-spine open book"],
  ["seed:0019", "Child's pose", "cooldown", "stretch"],
  ["seed:0020", "Foam rolling – back", "warmup", "foam roller thoracic"],
  ["seed:0021", "Foam rolling – legs", "warmup", "foam roller quads it band"],
  ["seed:0022", "Band pull-apart", "warmup", "banded shoulder"],
  ["seed:0023", "Band dislocates", "warmup", "banded shoulder pass-through"],
  ["seed:0024", "Banded standing flies", "warmup", "banded shoulder reverse fly"],
  ["seed:0025", "Band external rotation", "warmup", "banded shoulder rotator cuff"],
  ["seed:0026", "Face pull", "any", "cable band rear delt"],
  ["seed:0027", "Scapular shrugs", "any", "scap pull-up hang shrug"],
  ["seed:0028", "Scapular push-up", "warmup", "scap"],
  ["seed:0029", "Dead hang", "any", "bar hang"],
  ["seed:0030", "Jefferson curl", "cooldown", "kettlebell spine flexion"],
  ["seed:0031", "Hamstring stretch", "cooldown", "band strap lying"],
  ["seed:0032", "Pigeon stretch", "cooldown", "hip glute"],
  ["seed:0033", "Walk", "cooldown", "walking"],
  ["seed:0034", "Bike", "any", "cycling stationary"],
  ["seed:0035", "Rower", "any", "rowing erg"],
  ["seed:0036", "Skipping", "warmup", "jump rope"],
  // upper push
  ["seed:0037", "Bench press", "main", "barbell flat"],
  ["seed:0038", "Incline bench press", "main", "barbell 40 degree incline"],
  ["seed:0039", "Dumbbell bench press", "main", "db flat"],
  ["seed:0040", "Incline dumbbell press", "main", "db"],
  ["seed:0041", "Overhead press", "main", "ohp military barbell shoulder"],
  ["seed:0042", "Dumbbell shoulder press", "main", "db overhead"],
  ["seed:0043", "Push-up", "any", "press-up"],
  ["seed:0044", "Dips", "main", "parallel bar"],
  ["seed:0045", "Lateral raise", "main", "db shoulder"],
  ["seed:0046", "Triceps pushdown", "main", "cable"],
  ["seed:0047", "Skull crusher", "main", "triceps extension"],
  // upper pull
  ["seed:0048", "Pull-up", "main", "chin weighted"],
  ["seed:0049", "Chin-up", "main", "pull-up supinated"],
  ["seed:0050", "Lat pulldown", "main", "cable"],
  ["seed:0051", "Barbell row", "main", "bent over"],
  ["seed:0052", "Dumbbell row", "main", "db single arm"],
  ["seed:0053", "Seated cable row", "main", "row"],
  ["seed:0054", "Inverted row", "main", "ring row bodyweight australian pull-up"],
  ["seed:0055", "Biceps curl", "main", "db barbell"],
  ["seed:0056", "Hammer curl", "main", "db"],
  // lower
  ["seed:0057", "Back squat", "main", "barbell"],
  ["seed:0058", "Front squat", "main", "barbell"],
  ["seed:0059", "Goblet squat", "main", "kettlebell dumbbell"],
  ["seed:0060", "Deadlift", "main", "barbell conventional"],
  ["seed:0061", "Romanian deadlift", "main", "rdl barbell dumbbell"],
  ["seed:0062", "Trap bar deadlift", "main", "hex bar"],
  ["seed:0063", "Hip thrust", "main", "barbell glute"],
  ["seed:0064", "Dumbbell lunges", "main", "walking lunge"],
  ["seed:0065", "Reverse lunge", "main"],
  ["seed:0066", "Bulgarian split squat", "main", "rear foot elevated rfess"],
  ["seed:0067", "Step-up", "main", "box"],
  ["seed:0068", "Leg press", "main", "machine"],
  ["seed:0069", "Leg curl", "main", "hamstring machine"],
  ["seed:0070", "Leg extension", "main", "quad machine"],
  ["seed:0071", "Nordic curl", "main", "hamstring"],
  ["seed:0072", "Calf raise", "main"],
  ["seed:0073", "Kettlebell swing", "main", "kb"],
  // core / carries
  ["seed:0074", "Hanging knee raise", "main", "abs"],
  ["seed:0075", "Hanging leg raise", "main", "abs"],
  ["seed:0076", "Ab wheel rollout", "main", "abs"],
  ["seed:0077", "Farmer carry", "main", "loaded carry walk"],
  ["seed:0078", "Suitcase carry", "main", "loaded carry"],
  // climbing
  ["seed:0079", "Hangboard", "main", "fingerboard max hang"],
  ["seed:0080", "Bouldering", "any", "climbing"],
  ["seed:0081", "Campus board", "main", "climbing"],
  ["seed:0082", "Finger extensions", "warmup", "rubber band extensor antagonist climbing"],
  // resistance band
  ["seed:0083", "Band row", "any", "banded seated standing low row"],
  ["seed:0084", "Band lat pulldown", "any", "banded kneeling"],
  ["seed:0085", "Straight-arm pulldown", "any", "cable band lat pullover"],
  ["seed:0086", "Band chest press", "any", "banded standing push"],
  ["seed:0087", "Band chest fly", "any", "banded pec"],
  ["seed:0088", "Band overhead press", "any", "banded shoulder press ohp"],
  ["seed:0089", "Band lateral raise", "any", "banded shoulder"],
  ["seed:0090", "Band biceps curl", "any", "banded"],
  ["seed:0091", "Band triceps pushdown", "any", "banded"],
  ["seed:0092", "Band overhead triceps extension", "any", "banded"],
  ["seed:0093", "Banded push-up", "main", "band resisted press-up"],
  ["seed:0094", "Band-assisted pull-up", "main", "banded assisted chin"],
  ["seed:0095", "Band-assisted dip", "main", "banded assisted"],
  ["seed:0096", "Band diagonal pull-apart", "warmup", "banded shoulder"],
  ["seed:0097", "Band internal rotation", "warmup", "banded shoulder rotator cuff"],
  ["seed:0098", "Band no-money", "warmup", "banded shoulder external rotation"],
  ["seed:0099", "Y-T-W raise", "warmup", "ytw prone band lower trap scapular"],
  ["seed:0100", "Woodchop", "any", "cable band rotation core"],
  ["seed:0101", "Band squat", "any", "banded"],
  ["seed:0102", "Band deadlift", "any", "banded"],
  ["seed:0103", "Band good morning", "any", "banded hinge hamstring"],
  ["seed:0104", "Band pull-through", "any", "banded cable hinge glute"],
  ["seed:0105", "Band glute kickback", "any", "banded donkey kick"],
  ["seed:0106", "Band leg curl", "any", "banded hamstring prone"],
  ["seed:0107", "Band hip abduction", "warmup", "banded glute med mini band seated standing"],
  ["seed:0108", "Lateral band walk", "warmup", "banded glute med mini band side step x-walk"],
  ["seed:0109", "Monster walk", "warmup", "banded glute med mini band"],
  ["seed:0110", "Band hip march", "warmup", "banded psoas hip flexor"],
  ["seed:0111", "Terminal knee extension", "warmup", "tke band knee vmo"],
  ["seed:0112", "Band ankle eversion", "warmup", "theraband ankle"],
  ["seed:0113", "Band ankle inversion", "warmup", "theraband ankle"],
  ["seed:0114", "Banded ankle mobilisation", "warmup", "band dorsiflexion distraction"],
  ["seed:0115", "Banded hip distraction", "warmup", "band hip mobilisation"],
  ["seed:0116", "Banded lat stretch", "cooldown", "band shoulder"],
  // calisthenics – push
  ["seed:0117", "Incline push-up", "any", "press-up box bench"],
  ["seed:0118", "Decline push-up", "main", "press-up feet elevated"],
  ["seed:0119", "Diamond push-up", "main", "close grip triangle press-up"],
  ["seed:0120", "Archer push-up", "main", "press-up"],
  ["seed:0121", "Pike push-up", "main", "press-up shoulder"],
  ["seed:0122", "Pseudo planche push-up", "main", "ppp press-up"],
  ["seed:0123", "One-arm push-up", "main", "single arm press-up"],
  ["seed:0124", "Clap push-up", "main", "plyo explosive press-up"],
  ["seed:0125", "Handstand push-up", "main", "hspu wall"],
  ["seed:0126", "Ring push-up", "main", "rings press-up"],
  ["seed:0127", "Ring dip", "main", "rings"],
  ["seed:0128", "Straight bar dip", "main"],
  ["seed:0129", "Bench dip", "main", "chair triceps"],
  // calisthenics – pull
  ["seed:0130", "Negative pull-up", "main", "eccentric chin"],
  ["seed:0131", "Archer pull-up", "main", "chin"],
  ["seed:0132", "L-sit pull-up", "main", "chin"],
  ["seed:0133", "Muscle-up", "main", "bar"],
  ["seed:0134", "Ring muscle-up", "main", "rings"],
  ["seed:0135", "Front lever", "main", "tuck advanced straddle hold"],
  ["seed:0136", "Front lever raise", "main", "lever"],
  ["seed:0137", "Back lever", "main", "tuck straddle hold"],
  ["seed:0138", "Skin the cat", "any", "rings shoulder"],
  ["seed:0139", "German hang", "warmup", "rings shoulder stretch"],
  // calisthenics – core and skills
  ["seed:0140", "Hollow body hold", "any", "hollow rock core"],
  ["seed:0141", "Arch hold", "any", "superman back"],
  ["seed:0142", "L-sit", "main", "parallettes tuck"],
  ["seed:0143", "Support hold", "any", "rings dip parallel bar"],
  ["seed:0144", "Toes to bar", "main", "t2b hanging abs"],
  ["seed:0145", "Dragon flag", "main", "abs"],
  ["seed:0146", "Windscreen wipers", "main", "hanging abs obliques"],
  ["seed:0147", "V-up", "main", "abs"],
  ["seed:0148", "Handstand", "any", "wall freestanding chest-to-wall hold"],
  ["seed:0149", "Wall walk", "any", "handstand"],
  ["seed:0150", "Crow pose", "any", "frog stand"],
  ["seed:0151", "Planche lean", "main", "planche"],
  ["seed:0152", "Tuck planche", "main", "planche"],
  ["seed:0153", "Wrist mobility", "warmup", "wrist warm-up"],
  ["seed:0154", "Bear crawl", "warmup"],
  // calisthenics – legs and jumps
  ["seed:0155", "Bodyweight squat", "any", "air squat"],
  ["seed:0156", "Pistol squat", "main", "single leg box"],
  ["seed:0157", "Shrimp squat", "main", "skater single leg"],
  ["seed:0158", "Cossack squat", "any", "side lateral"],
  ["seed:0159", "Sissy squat", "main", "quad"],
  ["seed:0160", "Reverse Nordic", "main", "quad"],
  ["seed:0161", "Wall sit", "any", "isometric quad"],
  ["seed:0162", "Tibialis raise", "any", "tib shin"],
  ["seed:0163", "Jump squat", "main", "plyo"],
  ["seed:0164", "Box jump", "main", "plyo"],
  ["seed:0165", "Broad jump", "main", "plyo long jump"],
  ["seed:0166", "Burpee", "any"],
  // flexibility
  ["seed:0167", "Pike stretch", "cooldown", "forward fold hamstring compression"],
  ["seed:0168", "Pancake stretch", "cooldown", "straddle"],
  ["seed:0169", "Bridge", "any", "wheel back bend"],
  // other activity
  ["seed:0170", "Run", "activity", "running jogging"],
  ["seed:0171", "Tennis", "activity"],
  ["seed:0172", "Yoga", "activity"],
  ["seed:0173", "Ride", "activity", "cycling outdoors"],
  ["seed:0174", "Swim", "activity", "swimming"],
  ["seed:0175", "Hike", "activity", "hiking"],
  ["seed:0176", "Mobility", "activity"],
];
