import type { Section } from "./types";

/**
 * Starter exercise list for search. Anything typed that isn't here is saved as-is
 * and shows up in search from then on.
 * [name, section hint, aliases]
 */
export type Seed = [string, Section | "any", string?];

export const SEEDS: Seed[] = [
  // mobility / warm-up / physio
  ["Cat cow", "warmup", "cat camel spine"],
  ["Standing knee to chest", "warmup"],
  ["Kneeling knee to chest", "warmup"],
  ["Plank knee to elbow", "warmup", "mountain climber"],
  ["Dead bug", "warmup", "core"],
  ["Bird dog", "warmup", "core"],
  ["Side plank", "warmup", "core"],
  ["Plank", "warmup", "core front"],
  ["Glute bridge", "warmup", "hip band"],
  ["Single-leg glute bridge", "warmup", "hip"],
  ["Clamshell", "warmup", "hip band"],
  ["McGill curl-up", "warmup", "core big 3"],
  ["Pallof press", "warmup", "core anti-rotation cable band"],
  ["Copenhagen plank", "warmup", "adductor core"],
  ["Hip flexor stretch", "warmup", "kneeling lunge stretch"],
  ["90/90 hip switch", "warmup", "hip mobility"],
  ["World's greatest stretch", "warmup"],
  ["Thoracic rotation", "warmup", "t-spine open book"],
  ["Child's pose", "cooldown", "stretch"],
  ["Foam rolling – back", "warmup", "foam roller thoracic"],
  ["Foam rolling – legs", "warmup", "foam roller quads it band"],
  ["Band pull-apart", "warmup", "banded shoulder"],
  ["Band dislocates", "warmup", "banded shoulder pass-through"],
  ["Banded standing flies", "warmup", "banded shoulder reverse fly"],
  ["Band external rotation", "warmup", "banded shoulder rotator cuff"],
  ["Face pull", "any", "cable band rear delt"],
  ["Scapular shrugs", "any", "scap pull-up hang shrug"],
  ["Scapular push-up", "warmup", "scap"],
  ["Dead hang", "any", "bar hang"],
  ["Jefferson curl", "cooldown", "kettlebell spine flexion"],
  ["Hamstring stretch", "cooldown", "band strap lying"],
  ["Pigeon stretch", "cooldown", "hip glute"],
  ["Walk", "cooldown", "walking"],
  ["Bike", "any", "cycling stationary"],
  ["Rower", "any", "rowing erg"],
  ["Skipping", "warmup", "jump rope"],
  // upper push
  ["Bench press", "main", "barbell flat"],
  ["Incline bench press", "main", "barbell 40 degree incline"],
  ["Dumbbell bench press", "main", "db flat"],
  ["Incline dumbbell press", "main", "db"],
  ["Overhead press", "main", "ohp military barbell shoulder"],
  ["Dumbbell shoulder press", "main", "db overhead"],
  ["Push-up", "any", "press-up"],
  ["Dips", "main", "parallel bar"],
  ["Lateral raise", "main", "db shoulder"],
  ["Triceps pushdown", "main", "cable"],
  ["Skull crusher", "main", "triceps extension"],
  // upper pull
  ["Pull-up", "main", "chin weighted"],
  ["Chin-up", "main", "pull-up supinated"],
  ["Lat pulldown", "main", "cable"],
  ["Barbell row", "main", "bent over"],
  ["Dumbbell row", "main", "db single arm"],
  ["Seated cable row", "main", "row"],
  ["Inverted row", "main", "ring row bodyweight australian pull-up"],
  ["Biceps curl", "main", "db barbell"],
  ["Hammer curl", "main", "db"],
  // lower
  ["Back squat", "main", "barbell"],
  ["Front squat", "main", "barbell"],
  ["Goblet squat", "main", "kettlebell dumbbell"],
  ["Deadlift", "main", "barbell conventional"],
  ["Romanian deadlift", "main", "rdl barbell dumbbell"],
  ["Trap bar deadlift", "main", "hex bar"],
  ["Hip thrust", "main", "barbell glute"],
  ["Dumbbell lunges", "main", "walking lunge"],
  ["Reverse lunge", "main"],
  ["Bulgarian split squat", "main", "rear foot elevated rfess"],
  ["Step-up", "main", "box"],
  ["Leg press", "main", "machine"],
  ["Leg curl", "main", "hamstring machine"],
  ["Leg extension", "main", "quad machine"],
  ["Nordic curl", "main", "hamstring"],
  ["Calf raise", "main"],
  ["Kettlebell swing", "main", "kb"],
  // core / carries
  ["Hanging knee raise", "main", "abs"],
  ["Hanging leg raise", "main", "abs"],
  ["Ab wheel rollout", "main", "abs"],
  ["Farmer carry", "main", "loaded carry walk"],
  ["Suitcase carry", "main", "loaded carry"],
  // climbing
  ["Hangboard", "main", "fingerboard max hang"],
  ["Bouldering", "any", "climbing"],
  ["Campus board", "main", "climbing"],
  ["Finger extensions", "warmup", "rubber band extensor antagonist climbing"],
  // resistance band
  ["Band row", "any", "banded seated standing low row"],
  ["Band lat pulldown", "any", "banded kneeling"],
  ["Straight-arm pulldown", "any", "cable band lat pullover"],
  ["Band chest press", "any", "banded standing push"],
  ["Band chest fly", "any", "banded pec"],
  ["Band overhead press", "any", "banded shoulder press ohp"],
  ["Band lateral raise", "any", "banded shoulder"],
  ["Band biceps curl", "any", "banded"],
  ["Band triceps pushdown", "any", "banded"],
  ["Band overhead triceps extension", "any", "banded"],
  ["Banded push-up", "main", "band resisted press-up"],
  ["Band-assisted pull-up", "main", "banded assisted chin"],
  ["Band-assisted dip", "main", "banded assisted"],
  ["Band diagonal pull-apart", "warmup", "banded shoulder"],
  ["Band internal rotation", "warmup", "banded shoulder rotator cuff"],
  ["Band no-money", "warmup", "banded shoulder external rotation"],
  ["Y-T-W raise", "warmup", "ytw prone band lower trap scapular"],
  ["Woodchop", "any", "cable band rotation core"],
  ["Band squat", "any", "banded"],
  ["Band deadlift", "any", "banded"],
  ["Band good morning", "any", "banded hinge hamstring"],
  ["Band pull-through", "any", "banded cable hinge glute"],
  ["Band glute kickback", "any", "banded donkey kick"],
  ["Band leg curl", "any", "banded hamstring prone"],
  ["Band hip abduction", "warmup", "banded glute med mini band seated standing"],
  ["Lateral band walk", "warmup", "banded glute med mini band side step x-walk"],
  ["Monster walk", "warmup", "banded glute med mini band"],
  ["Band hip march", "warmup", "banded psoas hip flexor"],
  ["Terminal knee extension", "warmup", "tke band knee vmo"],
  ["Band ankle eversion", "warmup", "theraband ankle"],
  ["Band ankle inversion", "warmup", "theraband ankle"],
  ["Banded ankle mobilisation", "warmup", "band dorsiflexion distraction"],
  ["Banded hip distraction", "warmup", "band hip mobilisation"],
  ["Banded lat stretch", "cooldown", "band shoulder"],
  // calisthenics – push
  ["Incline push-up", "any", "press-up box bench"],
  ["Decline push-up", "main", "press-up feet elevated"],
  ["Diamond push-up", "main", "close grip triangle press-up"],
  ["Archer push-up", "main", "press-up"],
  ["Pike push-up", "main", "press-up shoulder"],
  ["Pseudo planche push-up", "main", "ppp press-up"],
  ["One-arm push-up", "main", "single arm press-up"],
  ["Clap push-up", "main", "plyo explosive press-up"],
  ["Handstand push-up", "main", "hspu wall"],
  ["Ring push-up", "main", "rings press-up"],
  ["Ring dip", "main", "rings"],
  ["Straight bar dip", "main"],
  ["Bench dip", "main", "chair triceps"],
  // calisthenics – pull
  ["Negative pull-up", "main", "eccentric chin"],
  ["Archer pull-up", "main", "chin"],
  ["L-sit pull-up", "main", "chin"],
  ["Muscle-up", "main", "bar"],
  ["Ring muscle-up", "main", "rings"],
  ["Front lever", "main", "tuck advanced straddle hold"],
  ["Front lever raise", "main", "lever"],
  ["Back lever", "main", "tuck straddle hold"],
  ["Skin the cat", "any", "rings shoulder"],
  ["German hang", "warmup", "rings shoulder stretch"],
  // calisthenics – core and skills
  ["Hollow body hold", "any", "hollow rock core"],
  ["Arch hold", "any", "superman back"],
  ["L-sit", "main", "parallettes tuck"],
  ["Support hold", "any", "rings dip parallel bar"],
  ["Toes to bar", "main", "t2b hanging abs"],
  ["Dragon flag", "main", "abs"],
  ["Windscreen wipers", "main", "hanging abs obliques"],
  ["V-up", "main", "abs"],
  ["Handstand", "any", "wall freestanding chest-to-wall hold"],
  ["Wall walk", "any", "handstand"],
  ["Crow pose", "any", "frog stand"],
  ["Planche lean", "main", "planche"],
  ["Tuck planche", "main", "planche"],
  ["Wrist mobility", "warmup", "wrist warm-up"],
  ["Bear crawl", "warmup"],
  // calisthenics – legs and jumps
  ["Bodyweight squat", "any", "air squat"],
  ["Pistol squat", "main", "single leg box"],
  ["Shrimp squat", "main", "skater single leg"],
  ["Cossack squat", "any", "side lateral"],
  ["Sissy squat", "main", "quad"],
  ["Reverse Nordic", "main", "quad"],
  ["Wall sit", "any", "isometric quad"],
  ["Tibialis raise", "any", "tib shin"],
  ["Jump squat", "main", "plyo"],
  ["Box jump", "main", "plyo"],
  ["Broad jump", "main", "plyo long jump"],
  ["Burpee", "any"],
  // flexibility
  ["Pike stretch", "cooldown", "forward fold hamstring compression"],
  ["Pancake stretch", "cooldown", "straddle"],
  ["Bridge", "any", "wheel back bend"],
];
